### ISSUE TITLE
Implement sshoogr main app that will be capable of running *.sshoogr scripts

### ISSUE THREAD

**Issue by aadamovich** [aestasit/sshoogr#40]
Those scripts are just plain Groovy with few magic imports added

**Comment by acsadam0404** [comment]
You can use groovy with Grab. 

Execute with ```groovy scriptfile.groovy```

```
@Grab('com.aestasit.infrastructure.sshoogr:sshoogr:0.9.18')
import static com.aestasit.infrastructure.ssh.DefaultSsh.*

options.trustUnknownHosts = true
options.failOnError = false
options.execOptions.failOnError = false

remoteSession(...) {
//       sshoogr magic
 }

```

**Comment by aadamovich** [comment]
The idea was to have executable that can be called like that:

      sshoogr --hosts=list_of_hosts.txt --trust=true --failOnError=false magic.sshoogr
