### ISSUE TITLE
Please provide a way to seed SSH configuration and host keys

### ISSUE THREAD

**Issue by nthykier** [aestasit/sshoogr#57]
Hi,

Please provide a way to seed SSH configuration and tell Jsch about host keys.  Currently, the following Jsch options are hardcoded[1]:

``` groovy
  config.put("StrictHostKeyChecking", "no")
  config.put("HashKnownHosts", "yes")
  config.put("PreferredAuthentications", "publickey,keyboard-interactive,password")
```

We would like to be able to enable StrictHostKeyChecking and provide the public key of the target host to Jsch. 

Thank you in advance,

[1]https://github.com/aestasit/sshoogr/blob/master/src/main/groovy/com/aestasit/ssh/dsl/SshDslEngine.groovy#L40

**Comment by pavel-kolesnikov** [comment]
Documentation? Commit?

**Comment by aadamovich** [comment]
https://github.com/sshoogr/sshoogr/blob/main/subprojects/sshoogr/src/main/groovy/com/aestasit/infrastructure/ssh/dsl/SshDslEngine.groovy#L49

**Comment by aadamovich** [comment]
options.trustUnknownHosts
