### ISSUE TITLE
Can't get keyFile working

### ISSUE THREAD

**Issue by wtfqm** [aestasit/sshoogr#65]
Hi, I am trying to use the keyFile feature but every time i get a "reject HostKey" even if I have tried multiples keys which works fine with ssh. My scripts looks like this:

remoteSession {
	user = 'joni01'
	keyFile = new File('/home/johan/.ssh/id_rsa')
	host = 'idx515'
	connect()
	exec 'ls /tmp/*'
}

But every time I get a:

>>> Connecting to idx515
Caught: com.jcraft.jsch.JSchException: reject HostKey: idx515

Even if "ssh -i /home/johan/.ssh/id_rsa joni01@idx515" works fine.

What am I missing? Do I need a certain type of key?

I am using 0.9.18.

**Comment by kphonik** [comment]
It's not your key being rejected but instead the host's key hasn't been accepted into your ~/.ssh/known_hosts.

I had no luck setting the trustUnknownHosts within the remoteSession closure itself so I had to set it on the static DefaultSsh.options instance beforehand:

```groovy
options.trustUnknownHosts = true
remoteSession {
    // etc...
}```

Obviously you shouldn't use this option with a truly unknown host but it should be fine for connecting to locally network hosts.

**Comment by wtfqm** [comment]
Thank you!
