### ISSUE TITLE
SshDslEngine should expose a way to disconnect the delegate if options.reuseConnection is true

### ISSUE THREAD

**Issue by rhuffman** [aestasit/sshoogr#77]
As noted in the README, applications can instantiate their own SshDslEngine. However, if they do so and they use options.resuseConnection = true, there is no way to explicitly disconnect the delegate. The first executeSession creates the delegate, and it will never be disconnected.

I think this should probably be in the form of a "release" or "close" method with no arguments on the SshDslEngine that would simply invoke SshDslEngine.safeDisconnect(delegate).

**Comment by aadamovich** [comment]
@rhuffman but there is a `disconnect()` method
