### ISSUE TITLE
Failed to grab @Grab('com.aestasit.infrastructure.sshoogr:sshoogr:0.9.25')

### ISSUE THREAD

**Issue by alexey-terentiev** [aestasit/sshoogr#80]
For some reason jansi 1.11 dependency can't be grabbed
```
15:38	0 Grape dependency jars added
			@Grab('com.aestasit.infrastructure.sshoogr:sshoogr:0.9.25'): 0 jars
			Error grabbing Grapes -- [download failed: org.fusesource.jansi#jansi;1.11!jansi.jar]
```
Forced to use older version of shoogr without this library: 0.9.21
P.S> The latest jansi 1.14 can be grabbed without any issues:
`15:42	1 Grape dependency jar added: @Grab('org.fusesource.jansi:jansi:1.14'): 1 jar`

**Comment by aadamovich** [comment]
upgraded to jansi 1.14
