### ISSUE TITLE
Add pronunciation of sshoogr

### ISSUE THREAD

**Issue by zrks** [aestasit/sshoogr#85]
We need conventional way on how to pronounce this libraries name properly

**Comment by caillette** [comment]
In French I would say "chougre" which is as silly as saying "gougle" for Google.
In English I guess that "sugar" is what the creators had in mind.
(Sshoogr is amazing. I say that, being a Groovy-hater since it earliest times.)

**Comment by aadamovich** [comment]
@caillette totally correct :) I added a note to README.md
